# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile
  pod 'Firebase/Core'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile-tvOS
  pod 'Firebase/Core'

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
